-- Reconstructed genesis baseline.
--
-- The seven original tables (profiles, organizers, trips, bookings,
-- booking_participants, reviews, waitlist) plus app_config were created directly
-- against the live database before migration tracking began, so no CREATE TABLE
-- for them exists anywhere in supabase/migrations. Without them a from-scratch
-- `supabase db reset` fails: the oldest tracked migration (20260518000000) indexes
-- trips, and 20260528000000 references app_config, neither of which exists yet.
--
-- This file rebuilds the GENESIS shape of those tables: their live definition in
-- prod_schema_dump.sql with everything later migrations add removed (added columns,
-- added constraints, added indexes), so that this file followed by every existing
-- migration in timestamp order lands on the current production schema. Where a
-- later migration re-adds a column with a different type, default, or nullability
-- than the live column, the column is kept here in its live form and the later
-- `ADD COLUMN IF NOT EXISTS` simply no-ops (see the report notes for the full list).
--
-- Timestamp 20260517000000 sorts before every existing migration.
--
-- Scope: CREATE TABLE plus identity clauses only. RLS, policies, grants, indexes,
-- functions, triggers, and seed data all live in their own later migrations and
-- are intentionally NOT reproduced here. app_config mirrors the CREATE TABLE from
-- 20260528000004_admin_config.sql (table only) so it exists before 20260528000000
-- needs it; that later migration then no-ops on the table.
--
-- FKs to auth.users are genesis and assume the Supabase auth schema exists, which
-- it does at db reset time. Tables are ordered so intra-file foreign keys resolve.

-- ============================================================================
-- profiles
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL PRIMARY KEY,
  birthdate date,
  created_at timestamptz DEFAULT now(),
  emergency_contact_name text,
  emergency_contact_phone text,
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-- ============================================================================
-- organizers
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.organizers (
  id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  user_id uuid NOT NULL,
  email text NOT NULL,
  full_name text NOT NULL,
  bio text NOT NULL,
  phone text NOT NULL,
  status text DEFAULT 'pending'::text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  photo_url text,
  display_name text,
  cover_image_url text,
  facebook_url text,
  past_trips_evidence text,
  activity_types text[],
  years_experience integer,
  emergency_certified boolean DEFAULT false,
  social_links jsonb,
  CONSTRAINT organizers_user_id_key UNIQUE (user_id),
  CONSTRAINT organizers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ============================================================================
-- trips
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.trips (
  id bigint NOT NULL PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  title text,
  slug text,
  activity_type text,
  description text,
  difficulty text,
  price numeric,
  total_slots integer,
  remaining_slots integer,
  date_start timestamptz,
  date_end timestamptz,
  meeting_point text,
  destination text,
  status text,
  photos text[],
  includes text,
  what_to_bring text,
  organizer_id uuid,
  min_downpayment numeric DEFAULT 0,
  cancellation_policy text DEFAULT 'flexible'::text,
  duration text,
  is_template boolean DEFAULT false,
  meeting_points jsonb DEFAULT '[]'::jsonb,
  waitlist_enabled boolean DEFAULT true,
  CONSTRAINT remaining_slots_non_negative CHECK (remaining_slots >= 0),
  CONSTRAINT trips_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.organizers(id)
);

ALTER TABLE public.trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME public.trips_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

-- ============================================================================
-- bookings
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint NOT NULL PRIMARY KEY,
  trip_id bigint,
  full_name text,
  email text,
  phone text,
  slots integer,
  total_amount numeric,
  status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamptz DEFAULT now(),
  payment_option text DEFAULT 'full'::text,
  amount_due numeric,
  participants jsonb,
  emergency_contact_name text,
  emergency_contact_phone text,
  medical_notes text,
  waiver_agreed boolean DEFAULT false,
  user_id uuid,
  meeting_point text,
  platform_waiver_agreed boolean DEFAULT false NOT NULL,
  refund_issued boolean DEFAULT false,
  refund_amount numeric(10,2),
  refund_status text,
  refunded_at timestamptz,
  transferred_at timestamptz,
  transferred_by uuid,
  CONSTRAINT fk_bookings_trip FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE RESTRICT,
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
  SEQUENCE NAME public.bookings_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

-- ============================================================================
-- booking_participants
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.booking_participants (
  id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  booking_id bigint,
  slot_number integer NOT NULL,
  token uuid DEFAULT gen_random_uuid() NOT NULL,
  full_name text,
  emergency_contact_name text,
  emergency_contact_phone text,
  medical_notes text,
  meeting_point text,
  waiver_accepted boolean DEFAULT false,
  waiver_accepted_at timestamptz,
  completed boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT booking_participants_token_key UNIQUE (token),
  CONSTRAINT booking_participants_token_unique UNIQUE (token),
  CONSTRAINT booking_participants_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE CASCADE
);

-- ============================================================================
-- reviews
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint NOT NULL PRIMARY KEY,
  trip_id bigint NOT NULL,
  booking_id bigint,
  user_id uuid NOT NULL,
  full_name text NOT NULL,
  rating integer NOT NULL,
  body text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  organizer_id uuid,
  CONSTRAINT reviews_rating_check CHECK ((rating >= 1) AND (rating <= 5)),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id) ON DELETE SET NULL,
  CONSTRAINT reviews_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT reviews_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE,
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME public.reviews_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

-- ============================================================================
-- waitlist
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.waitlist (
  id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
  trip_id bigint,
  user_id uuid,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  slots integer DEFAULT 1 NOT NULL,
  created_at timestamptz DEFAULT now(),
  notified boolean DEFAULT false,
  notified_at timestamptz,
  CONSTRAINT waitlist_trip_id_user_id_key UNIQUE (trip_id, user_id),
  CONSTRAINT waitlist_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id) ON DELETE CASCADE,
  CONSTRAINT waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ============================================================================
-- app_config
-- Mirrors the table definition in 20260528000004_admin_config.sql (table only),
-- so it exists before 20260528000000 references it. The later migration then
-- no-ops on the table via its own CREATE TABLE IF NOT EXISTS.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.app_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  value text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- ============================================================================
-- GENESIS INDEXES
--
-- Indexes that exist in prod_schema_dump.sql but are created by NO migration in
-- supabase/migrations. They were added directly to the live database and never
-- captured, so a from-scratch db reset would otherwise miss them. Definitions are
-- copied verbatim from the dump, converted to CREATE [UNIQUE] INDEX IF NOT EXISTS.
-- Indexes implied by PK/UNIQUE table constraints are already covered by the
-- CREATE TABLE statements above and are not repeated here.
--
-- EXCLUDED ON PURPOSE (two genesis-only bookings indexes cannot live in this file):
--   idx_bookings_payment_id          ON bookings (payment_id)
--   idx_bookings_balance_payment_id  ON bookings (balance_payment_id)
-- Both reference columns that do NOT exist yet at this timestamp: payment_id is
-- added later by 20260529000002 and balance_payment_id by 20260530000001. Placing
-- either here would make CREATE INDEX fail with "column does not exist" and abort
-- the whole reset. They belong in a trailing migration that runs after those
-- columns are added, not in the genesis baseline. They are reported, not written.
-- ============================================================================

CREATE UNIQUE INDEX IF NOT EXISTS bookings_trip_user_active_unique ON public.bookings USING btree (trip_id, user_id) WHERE (status = ANY (ARRAY['confirmed'::text, 'pending'::text]));

CREATE INDEX IF NOT EXISTS idx_booking_participants_booking_id ON public.booking_participants USING btree (booking_id);

CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON public.bookings USING btree (created_at);

CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings USING btree (status);

CREATE INDEX IF NOT EXISTS idx_reviews_trip_id ON public.reviews USING btree (trip_id);

CREATE UNIQUE INDEX IF NOT EXISTS reviews_user_trip_unique ON public.reviews USING btree (user_id, trip_id);
